groups:
- name: Kafka Alerts
  rules:
    - alert: KafkaHighRequestLatency
      expr: kafka_request_latency_ms > 100
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High Kafka request latency"
        description: "Kafka request latency is above 100ms for more than 1 minute."
        
    - alert: KafkaBrokerDown
      expr: up{job="kafka-brokers"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kafka broker down"
        description: "A Kafka broker has been down for more than 5 minutes."